apply_patches:
	cd poky/build; \
	cp ../../patches/hdmi-audio.cfg ../meta-rockchip/recipes-kernel/linux/linux-yocto; \
	cp ../../patches/rockchip.wks ../meta-rockchip/wic; \
	cp ../../patches/bblayers.conf ./conf/; \
	cp ../../patches/local.conf ./conf/
