#!/bin/sh
exec tail -n +3 $0

menuentry "Boot from UUID" {
    search --no-floppy --fs-uuid --set=root --hint='usb0,gpt2' --hint='mmcblk1,gpt2' --hint='nvme0n1,gpt2' B921B045-1DF0-41C3-AF44-4C6F280D3FAE
    echo    'Loading Linux 6.14.0-rc3 ...'
    linux /boot/vmlinuz-6.14.0-rc3 root=LABEL=rootfs rw rootwait rootdelay=10
    echo    'Loading initial ramdisk ...'
    initrd /boot/initrd.img-6.14.0-rc3
    echo    'Loading rk3399-rock-pi-4b.dtb'
    devicetree /boot/dtb/rockchip/rk3399-rock-pi-4b.dtb
}
